---
image: debian/stable
packages:
  - bash
  - mksh
  - yash
  - zsh
  - sharness
tasks:
  - test-bash: |
      cd libglarray.sh/regress/
      bash array.t
  - test-mksh: |
      cd libglarray.sh/regress/
      mksh array.t
  - test-yash: |
      cd libglarray.sh/regress/
      yash array.t
  - test-zsh: |
      cd libglarray.sh/regress/
      zsh array.t
triggers:
  - action: email
    condition: failure
    to: "<tleguern+libglarray@bouledef.eu>"
